[package]
name = "toy-service"
version = "0.1.0"
authors = ["n4to4 <n4to4k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.0", features = ["full"] }
